# Generated by Django 5.2.15 on 2026-07-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=60)),
                ('wape', models.FloatField()),
                ('wape_main', models.FloatField(null=True)),
                ('wape_minor', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40, unique=True)),
                ('value', models.FloatField()),
                ('label_vi', models.CharField(max_length=200)),
                ('label_en', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=30)),
                ('stockout_days', models.IntegerField()),
                ('shortfall', models.BigIntegerField()),
                ('carryover', models.BigIntegerField(default=0)),
                ('undeliverable', models.BigIntegerField(default=0)),
                ('replan_events', models.IntegerField(default=0)),
                ('penalty', models.BigIntegerField()),
                ('vs_naive', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('fuel', models.CharField(max_length=20)),
                ('volume_share', models.FloatField()),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=4)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('total_demand', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('product', models.CharField(max_length=4)),
                ('fuel', models.CharField(max_length=20)),
                ('weeks_ahead', models.IntegerField(default=1)),
                ('p50', models.FloatField()),
                ('p90', models.FloatField()),
                ('p95', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecast.station')),
            ],
            options={
                'indexes': [models.Index(fields=['station', 'product', 'date'], name='forecast_fo_station_e9834c_idx')],
            },
        ),
    ]
